project:
  output-dir: docs
  type: website

website:
  title: "refloraR"
  site-url: https://dboslab.github.io/refloraR-quarto-website/
  page-navigation: true
  reader-mode: true  
  favicon: "figures/refloraR_hex_sticker.png"
  navbar:
    search: true
    background: light
    collapse-below: lg
    type: light
    logo: "figures/refloraR_hex_sticker.png"
    href: index.qmd
    left:
      - text: Get Started
        href: get-started/index.qmd
      - text: Articles
        href: articles/index.qmd
      - text: News
        href: packages/refloraR/latest/news.md 
      - text: Reference
        href: reference.qmd
    right:
      - icon: github
        href: https://dboslab.github.io/refloraR-quarto-website/
        
  sidebar:
    - id: get-started
      title: Get Started
      collapse-level: 2
      style: "floating"
      align: left
      contents:
        - href: get-started/index.qmd
                
    - id: articles
      title: Articles
      collapse-level: 3
      align: left
      contents:
        - text: Overview
          href: articles/index.qmd
        - section: Summarize REFLORA collections
          contents:
          - text: Summarize all collections 
            href: articles/summarize_reflora_collections.qmd
          - text: Summarize specific collections
            href: articles/summarize_reflora_collections.qmd    
        - section: Download REFLORA specimen records
          contents:
          - text: Download all specimen records 
            href: articles/download_reflora_collections.qmd
          - text: Download specimen records for specific collections
            href: articles/download_reflora_collections.qmd 

format:
  html:
    toc: true
    embed-resources: true
    code-copy: true
    code-overflow: wrap
    code-toos: true
    css: styles.css
    eval: false
    theme:
      light: [spacelab, theme.scss]
      dark: [spacelab, theme-dark.scss]
    include-in-header: gtm-body.html
    include-before-body: gtm-head.html
